export const colors = [
  {
    optionOne: "green",
    optionTwo: "blue",
    optionThree: "red",
    optionFour: "white",
    color: "white",
    text: "green",
  },
  {
    optionOne: "brown",
    optionTwo: "blue",
    optionThree: "red",
    optionFour: "orange",
    color: "blue",
    text: "red",
  },
  {
    optionOne: "brown",
    optionTwo: "grey",
    optionThree: "yellow",
    optionFour: "green",
    color: "brown",
    text: "yellow",
  },
  {
    optionOne: "red",
    optionTwo: "black",
    optionThree: "yellow",
    optionFour: "maroon",
    color: "red",
    text: "white",
  },
  {
    optionOne: "red",
    optionTwo: "brown",
    optionThree: "blue",
    optionFour: "orange",
    color: "orange",
    text: "black",
  },
  {
    optionOne: "black",
    optionTwo: "green",
    optionThree: "red",
    optionFour: "yellow",
    color: "green",
    text: "blue",
  },
  {
    optionOne: "grey",
    optionTwo: "turquoise",
    optionThree: "black",
    optionFour: "yellow",
    color: "grey",
    text: "orange",
  },
  {
    optionOne: "green",
    optionTwo: "pink",
    optionThree: "blue",
    optionFour: "orange",
    color: "pink",
    text: "grey",
  },
  {
    optionOne: "yellow",
    optionTwo: "orange",
    optionThree: "green",
    optionFour: "blue",
    color: "yellow",
    text: "purple",
  },
  {
    optionOne: "red",
    optionTwo: "blue",
    optionThree: "purple",
    optionFour: "green",
    color: "purple",
    text: "blue",
  },
  {
    optionOne: "black",
    optionTwo: "blue",
    optionThree: "yellow",
    optionFour: "green",
    color: "yellow",
    text: "blue",
  },
  {
    optionOne: "red",
    optionTwo: "blue",
    optionThree: "purple",
    optionFour: "yellow",
    color: "red",
    text: "yellow",
  },
  {
    optionOne: "red",
    optionTwo: "blue",
    optionThree: "black",
    optionFour: "brown",
    color: "blue",
    text: "red",
  },
  {
    optionOne: "orange",
    optionTwo: "blue",
    optionThree: "purple",
    optionFour: "green",
    color: "green",
    text: "purple",
  },
  {
    optionOne: "black",
    optionTwo: "blue",
    optionThree: "purple",
    optionFour: "red",
    color: "purple",
    text: "black",
  },
  {
    optionOne: "red",
    optionTwo: "blue",
    optionThree: "white",
    optionFour: "orange",
    color: "orange",
    text: "blue",
  },
  {
    optionOne: "purple",
    optionTwo: "blue",
    optionThree: "black",
    optionFour: "green",
    color: "blue",
    text: "green",
  },
  {
    optionOne: "orange",
    optionTwo: "blue",
    optionThree: "red",
    optionFour: "green",
    color: "green",
    text: "orange",
  },
  {
    optionOne: "yellow",
    optionTwo: "blue",
    optionThree: "red",
    optionFour: "green",
    color: "blue",
    text: "yellow",
  },
];
